// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWG_C66KCqcLpeuNzMOQLsXBZHtGSZ81w',
    appId: '1:776732766413:web:a69c606ddd3d0a122bf984',
    messagingSenderId: '776732766413',
    projectId: 'b3fa-46a01',
    authDomain: 'b3fa-46a01.firebaseapp.com',
    storageBucket: 'b3fa-46a01.appspot.com',
    measurementId: 'G-5V16E92YWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2no0JGZEPIXFJ3iHBLcewFhXxW7vdeeY',
    appId: '1:776732766413:android:d76ee5cc81dfb7b02bf984',
    messagingSenderId: '776732766413',
    projectId: 'b3fa-46a01',
    storageBucket: 'b3fa-46a01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvutKlUN4nqvbN2Fo5vj3Ban7S-KOXDU',
    appId: '1:776732766413:ios:24f2f8518018c6eb2bf984',
    messagingSenderId: '776732766413',
    projectId: 'b3fa-46a01',
    storageBucket: 'b3fa-46a01.appspot.com',
    iosBundleId: 'com.ebefa.ebefa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvutKlUN4nqvbN2Fo5vj3Ban7S-KOXDU',
    appId: '1:776732766413:ios:60c8d98da97ecfe52bf984',
    messagingSenderId: '776732766413',
    projectId: 'b3fa-46a01',
    storageBucket: 'b3fa-46a01.appspot.com',
    iosBundleId: 'com.ebefa.ebefa.RunnerTests',
  );
}
